apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    name: postgres-pod
    app: demo-voting-app
spec:
  containers:
    - name: postgres
      image: postgres:12-alpine
      resources:
        limits:
          memory: "100Mi"
          cpu: "150m"
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
