apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod
  labels:
    name: result-app
    app: demo-voting-app
spec:
  containers:
    - name: result-app
      image: docker/example-voting-app-result
      resources:
        limits:
          memory: "100Mi"
          cpu: "150m"
      ports:
        - containerPort: 80
