apiVersion: v1
kind: Pod
metadata:
  name: voting-app-pod
  labels:
    name: voting-app
    app: demo-voting-app
spec:
  containers:
    - name: voting-app
      image: docker/example-voting-app-vote
      resources:
        limits:
          memory: "100Mi"
          cpu: "150m"
      ports:
        - containerPort: 80
